# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnRrwIwqaBlO7vSHDk3prIWJ80RSl8QZ
"""

print("hello world ")

print("hello  world",end="$")
print("hello ayush")
print("regex")

#comment here - dynamic typed
# int variable=value
x=10
print(x,type(x))

x="10"
print(x,type(x))

x='10'
print(type(x))

#multi line string=> """ """
address="""b35 basant bahar
gopalpura bypass"""
print(address)

# hey
# dsalf
'''
'''

# string formatting
#%d, %s
year=2015
company="regex software"
print("year is ",year,"company name is ",company)

print(f"year is{year}Company name is {company}")

x=f"year is {year} Company name is {company}"
print(x)

username="regex"
msg=f"hey user {username}"
print(msg)
username="aman"
print(msg)

state="RAJASTHAN"
state[-1:-4:-1]